# Generated by Django 3.2 on 2023-09-10 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$')], verbose_name='Имя пользователя'),
        ),
    ]
