# Generated by Django 3.2 on 2023-09-14 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_unique_username_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_email',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email')},
        ),
    ]
