# Generated by Django 3.2 on 2023-09-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230909_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Рейтинг'),
        ),
    ]
